version: "3.8"

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client.dev
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
    networks:
      - frontend
    depends_on:
      - web_backend
      - scheduler
  web_backend:
    build:
      context: .
      dockerfile: Dockerfile.web_backend.dev
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app
      FLASK_ENV: development
      FLASK_CONFIG: DockerDevelopmentConfig
      FLASK_SECRET_KEY: supersupersecret
      FLASK_ADMIN_USERNAME: admin
      FLASK_ADMIN_PASSWORD: admin-password
      FLASK_SCHEDULER_USERNAME: scheduler
    volumes:
      - ./web_backend:/web_backend
    networks:
      - backend
      - frontend
    depends_on:
      - db
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile.scheduler.dev
    ports:
      - "4000:4000"
    volumes:
      - ./scheduler:/scheduler
    environment:
      FLASK_APP: app
      FLASK_ENV: development
      FLASK_CONFIG: DockerDevelopmentConfig
    networks:
      - backend
      - frontend
    depends_on:
      - db
      - web_backend
  db:
    image: postgres:14.3
    environment:
      - POSTGRES_USER=local_user
      - POSTGRES_PASSWORD=dev_password
      - POSTGRES_DB=local_db
    command: postgres -c listen_addresses='*'
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
  frontend:
