version: "3.8"

services:
  web_backend:
    build:
      context: .
      dockerfile: Dockerfile.web_backend.dev
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app
      FLASK_ENV: development
      FLASK_CONFIG: DockerDevelopmentConfig
    volumes:
      - ./web_backend:/web_backend
    networks:
      - backend
    depends_on:
      - db
  db:
    image: postgres:14.3
    environment:
      - POSTGRES_USER=local_user
      - POSTGRES_PASSWORD=dev_password
      - POSTGRES_DB=local_db
    command: postgres -c listen_addresses='*'
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
