FROM node:16.14-slim AS build_stage

WORKDIR /code/client

COPY ./client .
RUN npm run build

FROM nginx:1.23.0

COPY --from=build_stage /code/client/build /usr/share/nginx/html
COPY ./client/default.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]
