FROM python:3.10-slim

RUN apt-get update \
  && apt-get install -y postgresql-client \
  && apt-get install -y build-essential python-dev \
  && rm -rf /var/lib/apt/lists/*

COPY web_backend/requirements.txt .

RUN pip install -U pip wheel \
  && pip install -r requirements.txt

WORKDIR /web_backend

CMD ["bash", "-c", "flask db upgrade && flask --debug run --host=0.0.0.0"]
