FROM python:3.10-slim

RUN apt-get update \
  && apt-get install -y build-essential python-dev \
  && rm -rf /var/lib/apt/lists/*

COPY scheduler/requirements.txt .

RUN pip install -U pip wheel \
  && pip install -r requirements.txt

WORKDIR /scheduler

COPY scheduler .

ENV FLASK_CONFIG ProductionConfig
CMD ["uwsgi", "uwsgi.ini"]
