version: "3.8"

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client.prod
    ports:
      - "80:80"
    networks:
      - frontend
    depends_on:
      - web_backend
      - scheduler
  web_backend:
    build:
      context: .
      dockerfile: Dockerfile.web_backend.prod
    ports:
      - "5000:5000"
    environment:
      SQLALCHEMY_DATABASE_URI: "postgresql://local_user:dev_password@db:5432/local_db"
    volumes:
      - ./web_backend:/web_backend
    networks:
      - backend
      - frontend
    depends_on:
      - db
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile.scheduler.prod
    ports:
      - "4000:4000"
    volumes:
      - ./scheduler:/scheduler
    environment:
      SQLALCHEMY_DATABASE_URI: "postgresql://local_user:dev_password@db:5432/local_db"
    networks:
      - backend
      - frontend
    depends_on:
      - db
      - web_backend
  db:
    image: postgres:14.3
    environment:
      - POSTGRES_USER=local_user
      - POSTGRES_PASSWORD=dev_password
      - POSTGRES_DB=local_db
    command: postgres -c listen_addresses='*'
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
  frontend:
