FROM python:3.10-slim

RUN apt-get update \
  && apt-get install -y build-essential python-dev \
  && rm -rf /var/lib/apt/lists/*

COPY web_backend/requirements.txt .

RUN pip install -U pip wheel \
  && pip install -r requirements.txt

WORKDIR /web_backend

COPY web_backend .

ENV FLASK_APP app
ENV FLASK_CONFIG ProductionConfig
CMD ["bash", "-c", "flask db upgrade && uwsgi uwsgi.ini"]
