apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment-prod
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: client-prod
  template:
    metadata:
      labels:
        app: client-prod
    spec:
      containers:
        - name: client-prod
          image: registry.cloud.okteto.net/marketplace-zhoujc999/marketplace-client:latest
          resources:
            limits:
              cpu: "1"
              memory: "3Gi"
            requests:
              cpu: "1"
              memory: "3Gi"
          ports:
            - containerPort: 3000
