apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-deployment-prod
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 2
  selector:
    matchLabels:
      app: scheduler-prod
  template:
    metadata:
      labels:
        app: scheduler-prod
    spec:
      containers:
        - name: scheduler-prod
          image: registry.cloud.okteto.net/zhoujc999/marketplace-scheduler:latest
          volumeMounts:
            # name must match the volume name below
            - name: sqlalchemy-database-uri-secret
              mountPath: /var
              readOnly: true
          resources:
            limits:
              cpu: "1"
              memory: "2Gi"
            requests:
              cpu: "1"
              memory: "2Gi"
          ports:
            - containerPort: 4000
          env:
            - name: FLASK_ENV
              value: production
            - name: CONFIG_ENV
              value: prod.py
      # The secret data is exposed to Containers in the Pod through a Volume.
      volumes:
        - name: sqlalchemy-database-uri-secret
          secret:
            secretName: sqlalchemy-database-uri-secret
