apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-deployment-prod
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: scheduler-prod
  template:
    metadata:
      labels:
        app: scheduler-prod
    spec:
      containers:
        - name: scheduler-prod
          image: registry.cloud.okteto.net/marketplace-zhoujc999/marketplace-scheduler:latest
          volumeMounts:
            # name must match the volume name below
            - name: secrets
              mountPath: /var
              readOnly: true
          resources:
            limits:
              cpu: "1"
              memory: "2Gi"
            requests:
              cpu: "1"
              memory: "2Gi"
          ports:
            - containerPort: 4000
          env:
            - name: FLASK_ENV
              value: production
            - name: FLASK_CONFIG
              value: ProductionConfig
      # The secret data is exposed to Containers in the Pod through a Volume.
      volumes:
        - name: secrets
          projected:
            sources:
              - secret:
                  name: sqlalchemy-database-uri-secret
