apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-backend-deployment-prod
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: web-backend-prod
  template:
    metadata:
      labels:
        app: web-backend-prod
    spec:
      containers:
        - name: web-backend-prod
          image: registry.cloud.okteto.net/marketplace-zhoujc999/marketplace-web-backend:latest
          volumeMounts:
            # name must match the volume name below
            - name: secrets
              mountPath: /var
              readOnly: true
          resources:
            limits:
              cpu: "1"
              memory: "3Gi"
            requests:
              cpu: "1"
              memory: "3Gi"
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_CONFIG
              value: ProductionConfig
            - name: FLASK_ADMIN_USERNAME
              value: admin
            - name: FLASK_SCHEDULER_USERNAME
              value: scheduler
      # The secret data is exposed to Containers in the Pod through a Volume.
      volumes:
        - name: secrets
          projected:
            sources:
              - secret:
                  name: sqlalchemy-database-uri-secret
              - secret:
                  name: admin-password-secret
              - secret:
                  name: jwt-secret-key-secret
              - secret:
                  name: infura-provider-key-secret
              - secret:
                  name: platform-private-key-secret
              - secret:
                  name: mnemonic-api-key-secret
              - secret:
                  name: coinmarketcap-api-key-secret
