apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-backend-deployment-prod
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 2
  selector:
    matchLabels:
      app: web-backend-prod
  template:
    metadata:
      labels:
        app: web-backend-prod
    spec:
      containers:
        - name: web-backend-prod
          image: registry.cloud.okteto.net/marketplace-zhoujc999/marketplace-web-backend:latest
          volumeMounts:
            # name must match the volume name below
            - name: sqlalchemy-database-uri-secret
              mountPath: /var
              readOnly: true
            - name: admin-password-secret
              mountPath: /var
              readOnly: true
            - name: jwt-secret-key-secret
              mountPath: /var
              readOnly: true
          resources:
            limits:
              cpu: "1"
              memory: "2Gi"
            requests:
              cpu: "1"
              memory: "2Gi"
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: production
            - name: CONFIG_ENV
              value: prod.py
      # The secret data is exposed to Containers in the Pod through a Volume.
      volumes:
        - name: sqlalchemy-database-uri-secret
          secret:
            secretName: sqlalchemy-database-uri-secret
        - name: admin-password-secret
          secret:
            secretName: admin-password-secret
        - name: jwt-secret-key-secret
          secret:
            secretName: jwt-secret-key-secret
