import { Theme } from "../reduxSlices/themeSlice";
const themes = {
  [Theme.DARK]: {
    "--theme-color": "#3E3F3E",
    "--theme-bg-color": "#1f1f1f",
    "--theme-bg-color2": "#242424",
    "--theme-font-color": "#fff",
    "--theme-font-light-color": "#DEDEDE",
    "--theme-font-light-color2": "#979797",
    "--theme-usercenter-menu-bgcolor": "#1B1B1B",
    "--theme-usercenter-menu-hoverbgcolor": "#3279CC",
    "--theme-usercenter-menu-hovercolor": "#fff",
    "--theme-blue-color": "#3279CC",
    "--theme-scroll-navbar": "#000",
    "--home-table-border": "#000",
    "--menu-color": "#eee",
    "--home-data-bgcolor": "rgb(36, 36, 36)",
    "--home-table-headcolor": "#2a2c2f",
    "--home-table-headfontcolor": "#3279cc",
    "--home-table-trbgcolor": "rgb(53, 55, 57)",
    "--home-banner-button-bg": "#353739",
    "--pay-table-headbg": "#2a2c2f",
    "--pay-table-trbg": "",
    "--border-color": "#2b2b2b",
    "--border-color2": "#4C4C4C",
  },
  [Theme.LIGHT]: {
    "--theme-color": "rgb(241,244,247)",
    "--theme-bg-color2": "#fff",
    "--theme-bg-color": "rgb(250,250,250)",
    "--theme-font-color": "rgb(30, 73, 105)",
    "--theme-font-color2": "rgb(164, 180, 190)",
    "--theme-font-light-color": "#666",
    "--theme-font-light-color2": "#999",
    "--theme-usercenter-menu-bgcolor": "#fff",
    "--theme-usercenter-menu-hoverbgcolor": "#3279CC",
    "--theme-usercenter-menu-hovercolor": "#fff",
    "--theme-blue-color": "#3279CC",
    "--theme-scroll-navbar": "#fff",
    "--home-table-border": "#D6E1EB",
    "--menu-color": "#666",
    "--home-data-bgcolor": "transparent",
    "--home-table-headcolor": "#408DE8",
    "--home-table-headfontcolor": "#fff",
    "--home-table-trbgcolor": "#fff",
    "--home-banner-button-bg": "#fff",
    "--pay-table-headbg": "#F5F7F9",
    "--pay-table-trbg": "",
    "--border-color": "#eeeeee",
    "--border-color2": "#ddd",
  },
};
export default themes;
