"""Use signature instead of password.

Revision ID: 017b4db9672d
Revises: f8abbbe7490e
Create Date: 2022-07-21 02:12:49.993252

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "017b4db9672d"
down_revision = "f8abbbe7490e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("buyer", sa.Column("nonce", sa.String(), nullable=False))
    op.add_column("buyer", sa.Column("nonce_expiration_timestamp", postgresql.TIMESTAMP(), nullable=False))
    op.drop_column("buyer", "password_hash")
    op.drop_column("buyer", "salt")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("buyer", sa.Column("salt", postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.add_column("buyer", sa.Column("password_hash", postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.drop_column("buyer", "nonce_expiration_timestamp")
    op.drop_column("buyer", "nonce")
    # ### end Alembic commands ###
