"""Add an ownership table that records the number of shares that each buyer has.

Revision ID: 09f1674478b1
Revises: f4c458351308
Create Date: 2022-07-04 00:57:22.604921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "09f1674478b1"
down_revision = "f4c458351308"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ownership",
        sa.Column("buyer_name", sa.String(), nullable=False),
        sa.Column("deal_serial_id", sa.Integer(), nullable=False),
        sa.Column("shares", sa.Integer(), sa.CheckConstraint("shares >= 0"), nullable=False),
        sa.ForeignKeyConstraint(["buyer_name"], ["buyer.name"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["deal_serial_id"], ["deal.serial_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("buyer_name", "deal_serial_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ownership")
    # ### end Alembic commands ###
