"""Allow deal to have a multiplier that's not 1.

Revision ID: 2dbbfbb39bc7
Revises: 36b8c3269e8e
Create Date: 2022-08-10 01:20:50.418969

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "2dbbfbb39bc7"
down_revision = "36b8c3269e8e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("deal", sa.Column("multiplier", sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("deal", "multiplier")
    # ### end Alembic commands ###
