"""Change nft_id to two columns.

Revision ID: 36b8c3269e8e
Revises: 7b39b850efc6
Create Date: 2022-08-10 00:52:05.069079

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "36b8c3269e8e"
down_revision = "7b39b850efc6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("deal", sa.Column("collection_id", sa.String(), nullable=False))
    op.add_column("deal", sa.Column("asset_id", sa.String(), nullable=True))
    op.drop_column("deal", "nft_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("deal", sa.Column("nft_id", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column("deal", "asset_id")
    op.drop_column("deal", "collection_id")
    # ### end Alembic commands ###
