"""empty message

Revision ID: 4647d62ae349
Revises:
Create Date: 2022-06-26 18:58:11.111241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4647d62ae349"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("counter", sa.Column("number", sa.Integer(), nullable=False), sa.PrimaryKeyConstraint("number"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("counter")
    # ### end Alembic commands ###
