"""Modify allowed rates to rate

Revision ID: 5930943b5645
Revises: 6a4491a098fd
Create Date: 2022-08-25 11:58:17.942325

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5930943b5645"
down_revision = "6a4491a098fd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("deal", sa.Column("rate", sa.Float(), nullable=False))
    op.add_column("deal", sa.Column("extra_info", postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column("deal", sa.Column("collection_name", sa.String(), nullable=True))
    op.create_index(op.f("ix_deal_collection_name"), "deal", ["collection_name"], unique=False)
    op.drop_column("deal", "allowed_rates")
    op.drop_column("transaction", "rate")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transaction", sa.Column("rate", postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False)
    )
    op.add_column(
        "deal",
        sa.Column(
            "allowed_rates",
            postgresql.ARRAY(postgresql.DOUBLE_PRECISION(precision=53)),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_index(op.f("ix_deal_collection_name"), table_name="deal")
    op.drop_column("deal", "collection_name")
    op.drop_column("deal", "extra_info")
    op.drop_column("deal", "rate")
    # ### end Alembic commands ###
