"""Add a column to platform transaction for amount without fees

Revision ID: 6a4491a098fd
Revises: 2dbbfbb39bc7
Create Date: 2022-08-21 16:41:22.913897

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "6a4491a098fd"
down_revision = "2dbbfbb39bc7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("platform_transaction", sa.Column("amount_without_fees", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("platform_transaction", "amount_without_fees")
    # ### end Alembic commands ###
