"""Need reference asset prices in many tables

Revision ID: 7624d066d067
Revises: b37ac8239e55
Create Date: 2022-07-01 02:49:40.685887

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7624d066d067"
down_revision = "b37ac8239e55"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("deal", sa.Column("open_asset_price", sa.Float(), nullable=True))
    op.add_column("deal", sa.Column("closed_asset_price", sa.Float(), nullable=True))
    op.add_column("transaction", sa.Column("asset_price", sa.Float(), nullable=True))
    op.drop_column("transaction", "close_timestamp")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transaction", sa.Column("close_timestamp", postgresql.TIMESTAMP(), autoincrement=False, nullable=False)
    )
    op.drop_column("transaction", "asset_price")
    op.drop_column("deal", "closed_asset_price")
    op.drop_column("deal", "open_asset_price")
    # ### end Alembic commands ###
