"""Add the platform transaction table

Revision ID: 7b39b850efc6
Revises: 4bb8601aedf7
Create Date: 2022-07-27 02:24:21.654090

"""
from datetime import datetime
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7b39b850efc6"
down_revision = "4bb8601aedf7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "platform_transaction",
        sa.Column("transaction_hash", sa.String(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("timestamp", postgresql.TIMESTAMP, nullable=False, default=datetime.utcnow),
        sa.Column("buyer_name", sa.String(), nullable=True),
        sa.Column("dealer_name", sa.String(), nullable=True),
        sa.Column("as_dealer", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM("PENDING", "APPROVED", "REJECTED", "ATTENTION_NEEDED", name="platformtransactionstatus"),
            nullable=False,
        ),
        sa.Column("verification_info", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["buyer_name"], ["buyer.name"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["dealer_name"], ["dealer.name"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("transaction_hash"),
    )
    op.create_index(op.f("ix_platform_transaction_status"), "platform_transaction", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_platform_transaction_status"), table_name="platform_transaction")
    op.drop_table("platform_transaction")
    # ### end Alembic commands ###
