"""Add is_nft_index column to the deal table

Revision ID: 87f4e5255d01
Revises: 1ac9bf701a0b
Create Date: 2022-09-20 17:35:39.464803

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "87f4e5255d01"
down_revision = "1ac9bf701a0b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("deal", sa.Column("is_nft_index", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("deal", "is_nft_index")
    # ### end Alembic commands ###
