"""empty message

Revision ID: b37ac8239e55
Revises: 4647d62ae349
Create Date: 2022-06-27 02:28:12.207348

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b37ac8239e55"
down_revision = "4647d62ae349"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "buyer",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("balance", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "dealer",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("balance", sa.Float(), nullable=False),
        sa.Column("lockup_balance", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "deal",
        sa.Column("serial_id", sa.Integer(), nullable=False),
        sa.Column("dealer_name", sa.String(), nullable=True),
        sa.Column("nft_id", sa.String(), nullable=False),
        sa.Column("share_price", sa.Float(), nullable=False),
        sa.Column("allowed_rates", postgresql.ARRAY(sa.Float()), nullable=True),
        sa.Column("shares_remaining", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.TIMESTAMP(), nullable=False),
        sa.Column("end_time", sa.TIMESTAMP(), nullable=False),
        sa.Column("closed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dealer_name"],
            ["dealer.name"],
        ),
        sa.PrimaryKeyConstraint("serial_id"),
    )
    op.create_table(
        "platform_transaction",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("timestamp", sa.TIMESTAMP(), nullable=False),
        sa.Column("buyer_name", sa.String(), nullable=True),
        sa.Column("dealer_name", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["buyer_name"], ["buyer.name"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["dealer_name"], ["dealer.name"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "transaction",
        sa.Column("buyer_name", sa.String(), nullable=False),
        sa.Column("deal_serial_id", sa.Integer(), nullable=False),
        sa.Column("shares", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.TIMESTAMP(), nullable=False),
        sa.Column("rate", sa.Float(), nullable=False),
        sa.Column("close_timestamp", sa.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(["buyer_name"], ["buyer.name"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["deal_serial_id"], ["deal.serial_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("buyer_name", "deal_serial_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transaction")
    op.drop_table("platform_transaction")
    op.drop_table("deal")
    op.drop_table("dealer")
    op.drop_table("buyer")
    # ### end Alembic commands ###
