"""Make dealer also use signature instead of password

Revision ID: b844a5e1aeff
Revises: 017b4db9672d
Create Date: 2022-07-21 01:22:26.235563

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b844a5e1aeff"
down_revision = "017b4db9672d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("dealer", sa.Column("nonce", sa.String(), nullable=False))
    op.add_column("dealer", sa.Column("nonce_expiration_timestamp", postgresql.TIMESTAMP(), nullable=False))
    op.drop_column("dealer", "password_hash")
    op.drop_column("dealer", "salt")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("dealer", sa.Column("salt", postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.add_column("dealer", sa.Column("password_hash", postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.drop_column("dealer", "nonce_expiration_timestamp")
    op.drop_column("dealer", "nonce")
    # ### end Alembic commands ###
