"""Create password_hash and salt columns

Revision ID: cdc93828e33c
Revises: 09f1674478b1
Create Date: 2022-07-18 12:06:12.641748

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "cdc93828e33c"
down_revision = "09f1674478b1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("buyer", sa.Column("password_hash", postgresql.BYTEA(length=32), nullable=False))
    op.add_column("buyer", sa.Column("salt", postgresql.BYTEA(length=16), nullable=False))
    op.add_column("dealer", sa.Column("password_hash", postgresql.BYTEA(length=32), nullable=False))
    op.add_column("dealer", sa.Column("salt", postgresql.BYTEA(length=16), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dealer", "salt")
    op.drop_column("dealer", "password_hash")
    op.drop_column("buyer", "salt")
    op.drop_column("buyer", "password_hash")
    # ### end Alembic commands ###
