"""Adjust how amount and status is set

Revision ID: d8300c122587
Revises: 4bb8601aedf7
Create Date: 2022-07-24 18:30:17.294971

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d8300c122587"
down_revision = "4bb8601aedf7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("platform_transaction", sa.Column("as_dealer", sa.Boolean(), nullable=False))
    op.alter_column(
        "platform_transaction", "amount", existing_type=postgresql.DOUBLE_PRECISION(precision=53), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "platform_transaction", "amount", existing_type=postgresql.DOUBLE_PRECISION(precision=53), nullable=False
    )
    op.drop_column("platform_transaction", "as_dealer")
    # ### end Alembic commands ###
