"""Initial table creation

Revision ID: f4c458351308
Revises:
Create Date: 2022-07-03 16:54:31.991463

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f4c458351308"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "buyer",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("balance", sa.Float(), sa.CheckConstraint("balance >= 0"), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table("counter", sa.Column("number", sa.Integer(), nullable=False), sa.PrimaryKeyConstraint("number"))
    op.create_table(
        "dealer",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("balance", sa.Float(), sa.CheckConstraint("balance >= 0"), nullable=False),
        sa.Column("lockup_balance", sa.Float(), nullable=False),
        sa.CheckConstraint("lockup_balance <= balance"),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "deal",
        sa.Column("serial_id", sa.Integer(), nullable=False),
        sa.Column("dealer_name", sa.String(), nullable=True),
        sa.Column("nft_id", sa.String(), nullable=False),
        sa.Column("share_price", sa.Float(), sa.CheckConstraint("share_price > 0"), nullable=False),
        sa.Column("allowed_rates", postgresql.ARRAY(sa.Float()), nullable=True),
        sa.Column("shares_remaining", sa.Integer(), sa.CheckConstraint("shares_remaining >= 0"), nullable=False),
        sa.Column("open_asset_price", sa.Float(), sa.CheckConstraint("open_asset_price > 0"), nullable=True),
        sa.Column("closed_asset_price", sa.Float(), sa.CheckConstraint("closed_asset_price > 0"), nullable=True),
        sa.Column("start_time", postgresql.TIMESTAMP(), nullable=False),
        sa.Column("end_time", postgresql.TIMESTAMP(), nullable=False),
        sa.Column("closed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dealer_name"],
            ["dealer.name"],
        ),
        sa.PrimaryKeyConstraint("serial_id"),
    )
    op.create_table(
        "transaction",
        sa.Column("serial_id", sa.Integer(), nullable=False),
        sa.Column("buyer_name", sa.String(), nullable=False),
        sa.Column("asset_price", sa.Float(), sa.CheckConstraint("asset_price > 0"), nullable=True),
        sa.Column("deal_serial_id", sa.Integer(), nullable=False),
        sa.Column("shares", sa.Integer(), nullable=False),
        sa.Column("timestamp", postgresql.TIMESTAMP(), nullable=False),
        sa.Column("rate", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["buyer_name"], ["buyer.name"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["deal_serial_id"], ["deal.serial_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("serial_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transaction")
    op.drop_table("deal")
    op.drop_table("dealer")
    op.drop_table("counter")
    op.drop_table("buyer")
    # ### end Alembic commands ###
