"""Add the lockup balance information to the deal itself

Revision ID: f8abbbe7490e
Revises: cdc93828e33c
Create Date: 2022-07-18 19:05:19.065432

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f8abbbe7490e"
down_revision = "cdc93828e33c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "deal", sa.Column("lockup_balance", sa.Float(), sa.CheckConstraint("lockup_balance >= 0"), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("deal", "lockup_balance")
    # ### end Alembic commands ###
